## Ficha laboratorial – Discriminantes Logísticos e Máquinas de Suporte Vetorial

Ex1. Corre o código abaixo. 

In [510]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [511]:
BC = load_breast_cancer()
Xtrain,Xtest,ytrain,ytest = train_test_split(BC.data,BC.target)
print(ytrain.shape)
print(Xtrain.shape)
Dlog = LogisticRegression(max_iter=10000).fit(Xtrain,ytrain)
print(Dlog.score(Xtest,ytest))
print(Dlog.coef_)
print(Dlog.intercept_)
print(Dlog.n_iter_)

(426,)
(426, 30)
0.9440559440559441
[[ 0.73711406  0.12950362 -0.313972    0.03127723 -0.12069945 -0.13441614
  -0.4099928  -0.2419412  -0.18983837 -0.01606856 -0.10032958  0.96581387
   0.36396372 -0.14744845 -0.02305494  0.02768066 -0.05003055 -0.03523754
  -0.02314586  0.00353108 -0.18639436 -0.33253177 -0.13085005 -0.01071138
  -0.26616356 -0.40812282 -1.00049245 -0.48567928 -0.43608709 -0.06105703]]
[34.23720971]
[3155]


Observa e analisa os outputs e depois corre a instrução abaixo e verifica a grande 
diferença nos outputs: 

In [512]:
Dlog = LogisticRegression(solver='newton-cg',C=0.1,penalty='l2',max_iter=10000).fit(Xtrain,ytrain)
print(Dlog.score(Xtest,ytest))
print(Dlog.coef_)
print(Dlog.intercept_)
print(Dlog.n_iter_)

0.9440559440559441
[[ 8.52038563e-02  1.88067262e-02 -2.36454628e-01  3.71588568e-02
  -1.48693563e-02 -2.35666412e-02 -5.38463180e-02 -2.95223873e-02
  -2.28741808e-02 -3.02191669e-03 -1.11762645e-02  1.34801721e-01
   6.70417057e-02 -1.03596692e-01 -2.50263566e-03  3.92315094e-04
  -7.49197463e-03 -4.02097686e-03 -2.93981573e-03  6.83664056e-05
  -2.89979001e-02 -2.09387264e-01 -1.69954217e-01 -1.46518906e-02
  -3.16798278e-02 -7.70558931e-02 -1.38396340e-01 -5.94439023e-02
  -5.71299016e-02 -1.08299460e-02]]
[36.03493247]
[50]


Ex.2 Corre os dois códigos apresentados abaixo.

In [513]:
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix
Iris = load_iris()
Xtr,Xte,ytr,yte = train_test_split(Iris.data,Iris.target,test_size=1./3,random_state=0)


In [514]:
Dlog1 = LogisticRegression(solver='saga',C=0.1,penalty='l2',max_iter=1000).fit(Xtr,ytr)
print(Dlog1.coef_)
print(Dlog1.intercept_)
print(Dlog1.n_iter_)
yest = Dlog1.predict(Xte)
print(confusion_matrix(yte,yest))

[[-0.2430285   0.27855411 -0.99158363 -0.41028019]
 [ 0.04232199 -0.29727156  0.09375378 -0.14962848]
 [ 0.20070652  0.01871744  0.89782984  0.55990867]]
[ 4.40349261  1.23193827 -5.63543088]
[867]
[[16  0  0]
 [ 0 17  2]
 [ 0  1 14]]


Analisa os outputs e depois altera a “penalty” para “l1” e observa a diferença

In [515]:
Dlog1 = LogisticRegression(solver='saga',C=0.1,penalty='l1',max_iter=1000).fit(Xtr,ytr)
print(Dlog1.coef_)
print(Dlog1.intercept_)
print(Dlog.n_iter_)
yest = Dlog1.predict(Xte)
print(confusion_matrix(yte,yest))

[[ 0.          0.         -1.39744295  0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          1.15666211  0.        ]]
[ 4.54445089  0.47078672 -5.01523761]
[50]
[[16  0  0]
 [ 0 17  2]
 [ 0  0 15]]


Ex. 3  Corre o código abaixo e observa o valor obtido no desempenho:

In [516]:
from sklearn.svm import SVC
svm = SVC(kernel='rbf',gamma='auto').fit(Xtrain,ytrain)
print(svm.score(Xtest,ytest))

0.6713286713286714


A seguir corre o código abaixo e verifica o impacto do pré-processamento nos dados:

In [517]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(Xtrain,ytrain)
Xtrain1 = sc.transform(Xtrain); Xtest1 = sc.transform(Xtest)
svm1 = SVC(kernel='rbf',gamma='auto').fit(Xtrain1,ytrain)
print(svm1.score(Xtest1,ytest))

0.993006993006993
