In [264]:
import matplotlib.pyplot as plt
import numpy as np
import scipy.spatial.distance as spd
import pickle
from sklearn.metrics import confusion_matrix
from numpy.linalg import pinv


In [265]:
fName = 'A48168_Q002_data.p'
D = pickle.load(open(fName,'rb'))

## Pergunta 1

In [266]:
X = np.array([[3,3,4,1,0,1,2,1,1],
     [-1,-1,2,2,1,0,0,0,3]])
x0 = X[:,:5]
print(x0)
x1 = X[:,5:]
print(x1)

[[ 3  3  4  1  0]
 [-1 -1  2  2  1]]
[[1 2 1 1]
 [0 0 0 3]]


### alinea A

In [267]:
m0 = (np.mean(x0))
m1 = (np.mean(x1))
Xn0 = (X-m0)
Xn1 = (X-m1)
D0 = np.round(np.sqrt(np.sum(Xn0*Xn0,axis=0)))
D1 = np.round(np.sqrt(np.sum(Xn1*Xn1,axis=0)))
Dtotal = np.vstack((D0,D1))
estClass = np.round(np.argmin(Dtotal,axis=0))
y = [0,0,0,0,0,1,1,1,1]
MC = confusion_matrix(y,estClass)
print(MC)
print(np.sum(y!=estClass))

[[5 0]
 [3 1]]
3


## IV

### alinea B

In [268]:
cityDistance = np.sum(np.abs(m0-m1))
print(np.round(cityDistance,2))

pint = np.dot(m0.T,m1)
norm0 = np.linalg.norm(m0)
norm1 = np.linalg.norm(m1)
cosine = 1-(pint/(norm0*norm1))
print(np.round(cosine,2))

0.4
0.0


## IV

### alinea C

In [269]:
S0 = np.cov(x0)
S1 = np.cov(x1)

S0i = pinv(S0)
S1i = pinv(S1)

Xi = np.array([[-2],[1]])
Xii = np.array([[3],[1]])
Xc = np.hstack((Xi,Xii))
print(Xc)
D0a  = np.sqrt(np.sum((Xc-m0)*np.dot(S0i,Xc-m0), axis = 0))
print(D0a)
D1a  = np.sqrt(np.sum((Xc-m1)*np.dot(S1i,Xc-m1), axis = 0))
print(D1a)
Dtotal = np.vstack((D0a,D1a))
estClass = (np.argmin(Dtotal,axis=0))
print(estClass)

[[-2  3]
 [ 1  1]]
[2.23028439 0.97378157]
[6.36396103 4.24264069]
[0 0]


## IV

### alinea D

In [270]:
Xnew = np.array([[3,3,4,1,0,1,2,1,1],
               [-1,-1,2,2,1,0,0,0,3]])
Xnew0 = Xnew[:,:5]
Xnew1 = Xnew[:,5:]
print(Xnew0)
print(Xnew1)

[[ 3  3  4  1  0]
 [-1 -1  2  2  1]]
[[1 2 1 1]
 [0 0 0 3]]


In [271]:
mNew0 = np.mean(Xnew0,axis=1)
mNew1 = np.mean(Xnew1,axis=1)

Aux0 = np.dot(Xnew.T,mNew0)
D0 = 1 - Aux0/np.dot(np.sqrt(np.sum(Xnew**2)),np.sqrt(np.sum(mNew0**2)))
Aux1 = np.dot(Xnew.T,mNew1)
D1 = 1 - Aux1/np.dot(np.sqrt(np.sum(Xnew**2)),np.sqrt(np.sum(mNew1**2)))
yNew = np.array([0,0,0,0,0,1,1,1,1])
Dd  = np.vstack((D0, D1)) 
yed = np.argmin(Dd, axis=0) 
print(yed)
MC = confusion_matrix(yNew, yed)
print('Matriz de Confusão\n', MC)
TN = MC[0,0]
FP = MC[0,1]
FN = MC[1,0]
TP = MC[1,1]
print()
print('i)  acertos na classe dos positivos é de 4: ', TP)  # F
print('ii) O número total de erros é 1:', FN+FP) # V

[0 0 1 1 1 0 0 0 1]
Matriz de Confusão
 [[2 3]
 [3 1]]

i)  acertos na classe dos positivos é de 4:  1
ii) O número total de erros é 1: 6


## IV

## 2

In [272]:
fName = 'A48168_Q002_data.p'
D = pickle.load(open(fName,'rb'))

In [273]:
true_class = D['trueClass']
est_class = D['estClass']
# Cálculos dos totais
total_negativos = np.sum(true_class == 0)
total_positivos = np.sum(true_class == 1)
total_exemplos = len(true_class)

# Cálculo das métricas
true_negatives = np.sum((true_class == 0) & (est_class == 0))
false_negatives = np.sum((true_class == 1) & (est_class == 0))
false_positives = np.sum((true_class == 0) & (est_class == 1))

# Percentagem de acertos da classe dos negativos
percent_acertos_negativos = (true_negatives / total_negativos) * 100
percent_acertos_negativos = round(percent_acertos_negativos, 1)

# Percentagem de exemplos da classe dos positivos
percent_exemplos_positivos = (total_positivos / total_exemplos) * 100
percent_exemplos_positivos = round(percent_exemplos_positivos, 1)

# Resultados
print("Percentagem de acertos da classe dos negativos:", percent_acertos_negativos, "%")
print("Percentagem de exemplos da classe dos positivos:", percent_exemplos_positivos, "%")
print("Número de Falsos Negativos:", false_negatives)
print("Número de Falsos Positivos:", false_positives)

Percentagem de acertos da classe dos negativos: 79.1 %
Percentagem de exemplos da classe dos positivos: 20.0 %
Número de Falsos Negativos: 73
Número de Falsos Positivos: 334


a) ii

b) ii

In [274]:
q = pickle.load(open('A48168_Ficha2_Respostas.p','rb'))
print(q)

{'Q001': array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]]), 'Q002': array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]]), 'nome': 'Diogo Sancho Pires Lobo', 'numero': 'A48168'}


In [275]:
q['Q001'][0,:] = [0,0,0,1]
q['Q001'][1,:] = [0,0,0,1]
q['Q001'][2,:] = [0,0,0,1]
q['Q001'][3,:] = [0,0,0,1]

q['Q002'][0,:] = [0,1,0,0]
q['Q002'][1,:] = [0,1,0,0]

pickle.dump(q,open('A48168_Ficha2_Respostas.p','wb'))

In [276]:
vs = pickle.load(open('A48168_Ficha2_Respostas.p','rb'))
print(vs)

{'Q001': array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]]), 'Q002': array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]]), 'nome': 'Diogo Sancho Pires Lobo', 'numero': 'A48168'}
